### ISSUE TITLE
Error when using agent with EAP PEAP

### ISSUE THREAD

**Issue by atran-inverse** [inverse-inc/packetfence-windows-agent#8] opened 2018-07-06 21:09 UTC
When using PEAP as EAP type in the PacketFence Provisioner configuration, using the agent would give the error: The Certificate of Authority could not be installed on your machine, please contact your local support.

No CA is needed for PEAP.

![image](https://user-images.githubusercontent.com/36165527/42400224-b77bbb80-813e-11e8-9727-806249b05f8e.png)

![caerror](https://user-images.githubusercontent.com/36165527/42400365-4057e262-813f-11e8-836d-1ff35e2327dc.PNG)

**Comment by extrafu** [comment] 2018-07-09 12:45
Did a "retry window" appear after? Is your Windows user an administrator? If not, how about if you run the provisioning agent as an admin? It's not a permanent solution, but a test.

**Comment by atran-inverse** [comment] 2018-07-09 13:28
No "retry window" after. I tried running as an admin, but same results.

**Comment by nqb** [comment] 2018-07-09 13:30
On my side, I tested Windows provisioner with `EAP type=EAP-TLS` and a PKI provider supply by `packetfence-pki`. With a standard user on my Windows machine, I didn't get this error.

**Comment by extrafu** [comment] 2018-07-09 13:33
@nqb With the Golang-based provisioning agent or the Python one?

**Comment by nqb** [comment] 2018-07-09 14:06
Python.

-- 
Nicolas Quiniou-Briand
nqb@inverse.ca  ::  +1.514.447.4918 *140  ::  https://inverse.ca
Inverse inc. :: Leaders behind SOGo (https://sogo.nu), PacketFence 
(https://packetfence.org) and Fingerbank (http://fingerbank.org)

**Comment by extrafu** [comment] 2018-07-09 14:07
Please retry your EAP-TLS test using the Golang-based one.

**Comment by nqb** [comment] 2018-07-09 15:39
When using agent built by @atran-inverse on my Windows machine with my standard user, I need an admin account to launch the agent. Windows UAC prompt me a window to enter credentials. If I answer no, I can't continue. We didn't have this behavior with Python agent.

In spite of this limitation, I redo my test with `EAP type=EAP TLS` and Golang-based agent with my standard user.
I got following results : 
- No RADIUS server certificate imported : agent said that all was right
- No User certificate imported : agent said that all was right
- Network profile added with `Do not prompt user to authorize new servers or trusted certification` option checked. With Python, this option was unchecked.
=> I will create an issue for these unexpected behaviors.

With EAP type=PEAP`, I get same issue as @atran-inverse.

**Comment by extrafu** [comment] 2018-07-30 14:33
@nqb @atran-inverse @Zouelie I'll take care of this issue this week.

**Comment by extrafu** [comment] 2018-07-31 14:55
@nqb @atran-inverse @Zouelie This problem comes from the fact that PacketFence sends the RADIUS certificate in the mobile config XML file but tags it as a CA. That is incorrect and we don't need to do that. Using EAP-PEAP, we assume the CA is in place on the endpoint if the supplicant is configured to validate the RADIUS server certificate. By default, our PEAP provisioners disable that verification because PacketFence doesn't have access to the CA when doing PEAP (and thus, can't generate the mobile config XML including it).

I'll adjust the code so we do what we used to do - i.e. ignore PayloadType com.apple.security.root when EAP type isn't 13 (EAP-TLS).

**Comment by extrafu** [comment] 2018-07-31 15:17
@nqb @atran-inverse @Zouelie I've pushed a quick fix for this: https://github.com/inverse-inc/packetfence-windows-agent/commit/6a4dfc3df7951f530296bc1b1b92c08889b3f7e9

Note that the code should be slightly refactored as right now, it will fail if the RADIUS certificate content appears before the the WiFi/wired connection information in the mobile config profile. That shouldn't happen as PacketFence controls this but nonetheless, we should clean that up.

**Closed as completed** 2018-07-31 15:17 UTC

**Comment by extrafu** [comment] 2018-07-31 15:43
Also see: https://github.com/inverse-inc/packetfence/issues/3432
